# Generated by Django 4.2.3 on 2023-07-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdinarioModel',
            new_name='Ordinario',
        ),
    ]
