# Generated by Django 4.2.3 on 2023-08-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinario',
            name='tiene_distribucion_interna',
        ),
    ]
