# Generated by Django 4.2.3 on 2023-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0003_alter_ordinario_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionexterna',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='distribucionexterna',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
