# Generated by Django 4.2.3 on 2023-08-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0003_ordinario_distribuciones_externas_asociadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordinario',
            old_name='antecendente',
            new_name='antecedente',
        ),
    ]
