# Generated by Django 4.2.3 on 2023-08-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0005_alter_ordinario_antecedente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinario',
            name='distribuciones_externas_asociadas',
        ),
    ]
