# Generated by Django 4.2.3 on 2023-08-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0007_alter_ordinario_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinario',
            name='distribucion_interna',
            field=models.CharField(blank=True, null=True),
        ),
    ]
