# Generated by Django 4.2.3 on 2023-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0008_ordinario_distribucion_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinario',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
