# Generated by Django 4.2.3 on 2023-08-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinario', '0011_alter_ordinario_tipo_distribucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinario',
            name='tipo_distribucion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
